### ISSUE TITLE
Plugin does not work with other Liferay plugin

### ISSUE THREAD

**Issue by tzafarpk** [dmarks2/liferay-plugin-intellij#4]
Plugin is not working with official Liferay plugin.

On both plugins i am getting the same error (screenshot attached) if one is enabled and try to enable other one.

Even if i disable official Liferay plugin still plugin functionality is not working properly.

1. Freemarker Debugger refusing connection
2. Unable to set breakpoints in the **ftl** files.
3. autocompletion functionality is not working

![image](https://user-images.githubusercontent.com/11551585/82718683-67a77080-9cbd-11ea-871c-c1b5df738af9.png)

![image](https://user-images.githubusercontent.com/11551585/82718693-71c96f00-9cbd-11ea-9229-0d35e9070156.png)

![image](https://user-images.githubusercontent.com/11551585/82718786-1cda2880-9cbe-11ea-9d18-7477d26b11dc.png)

![image](https://user-images.githubusercontent.com/11551585/82718982-c66de980-9cbf-11ea-8a51-0fbc0a07c490.png)

**Comment by dmarks2** [comment]
Thank you @tzafarpk for your feedback.

My plugin and the official Liferay plugin cannot be installed at the same time, that is correct. I just updated the readme.md to clarify this. 

I will check if it is possible to have a technical check if the official Liferay plugin is installed and give a message or similar.

About the Freemarker stuff: Did you add the shown "Command line arguments" to the Run Configuration of your Liferay Server (e.g. Tomcat), as it is shown in the documentation here: https://github.com/dmarks2/liferay-plugin-intellij/blob/master/documentation/vtl_ftl_files.md#freemarker-debugger

Can you give me some examples which code completion features are not working properly?

**Comment by dmarks2** [comment]
It seems that it is possible to define the official Liferay plugin as a "replacement" for my plugin. So I will add a change which will show the following message when you try to install the official plugin. At least this will help to avoid some conflicts:

![image](https://user-images.githubusercontent.com/10325752/82800416-f7931900-9e7b-11ea-80a1-4189224a6c34.png)

**Comment by tzafarpk** [comment]
Hi @dmarks2 

I have tried the above instrutions for the debug connection and debugger is connected successfully but few of the below things still not working, i even disabled the other plugins (liferay and jrebel) and removed them but still functionality is not working.

I have tried these two and both autocompletions are not working:

1. [Implicit variables for Liferay Themes](https://github.com/dmarks2/liferay-plugin-intellij/blob/master/documentation/vtl_ftl_files.md#implicit-variables-for-liferay-themes)
2. [Implicit Theme Path variables](https://github.com/dmarks2/liferay-plugin-intellij/blob/master/documentation/vtl_ftl_files.md#implicit-theme-path-variables)

Unable to set breakpoints in **ftl** file

3. unable to set beakpoints in **ftl** file in liferay theme (Liferay CE 7.3) - theme created with `yo liferay-theme` npm plugin.

**Comment by dmarks2** [comment]
Thank you @tzafarpk for your feedback.

The root cause of all the problems you mention is that the folder "/src" is not detected as a source folder by IntelliJ. Many code completion features and the breakpoint functionality for freemarker templates require that the source folder is detected properly.

I just commited a change that tries to read the proper source folder from the gulpfile.js. When successfully it should mark the "/src" folder as a source folder (you should see a blue folder icon in front of the "src" directory).

If you want to test it immediately you can try to build the plugin yourself.

**Comment by dmarks2** [comment]
Issues should have been fixed in version 0.0.9 of the plugin.

Closing this issue.
